### ISSUE TITLE
Riscv-tools make failed for M1 support

### ISSUE THREAD

**Issue by mercurially** [riscv/riscv-tools#349]
Last 15 lines from /Users/zhangqiulei/Library/Logs/Homebrew/riscv-gnu-toolchain/04.make:
installing /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/po/vi.gmo as /opt/homebrew/Cellar/riscv-gnu-toolchain/master/share/locale/vi/LC_MESSAGES/opcodes.mo
install: /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/po/zh_CN.gmo: No such file or directory
installing /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/po/zh_CN.gmo as /opt/homebrew/Cellar/riscv-gnu-toolchain/master/share/locale/zh_CN/LC_MESSAGES/opcodes.mo
if test "opcodes" = "gettext"; then \
	  if test -r /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/../mkinstalldirs; then \
	    /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/../mkinstalldirs /opt/homebrew/Cellar/riscv-gnu-toolchain/master/share/gettext/po; \
	  else \
	    /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/mkinstalldirs /opt/homebrew/Cellar/riscv-gnu-toolchain/master/share/gettext/po; \
	  fi; \
	  /usr/bin/install -c -m 644 /private/tmp/riscv-gnu-toolchain-20211007-39509-1h96yof/riscv-gdb/opcodes/po/Makefile.in.in \
			  /opt/homebrew/Cellar/riscv-gnu-toolchain/master/share/gettext/po/Makefile.in.in; \
	else \
	  : ; \
	fi
mkdir -p stamps/ && touch stamps/build-gdb-newlib

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	25: from /opt/homebrew/Library/Homebrew/build.rb:229:in `<main>'
	24: from /opt/homebrew/Library/Homebrew/build.rb:133:in `install'
	23: from /opt/homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	22: from /opt/homebrew/Library/Homebrew/build.rb:138:in `block in install'
	21: from /opt/homebrew/Library/Homebrew/formula.rb:1275:in `brew'
	20: from /opt/homebrew/Library/Homebrew/formula.rb:2434:in `stage'
	19: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	18: from /opt/homebrew/Library/Homebrew/resource.rb:91:in `stage'
	17: from /opt/homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	16: from /opt/homebrew/Library/Homebrew/resource.rb:199:in `mktemp'
	15: from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	14: from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	13: from /opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	12: from /opt/homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	11: from /opt/homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
	10: from /opt/homebrew/Library/Homebrew/download_strategy.rb:110:in `chdir'
	 9: from /opt/homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 8: from /opt/homebrew/Library/Homebrew/formula.rb:2454:in `block in stage'
	 7: from /opt/homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	 6: from /opt/homebrew/Library/Homebrew/formula.rb:2455:in `block (2 levels) in stage'
	 5: from /opt/homebrew/Library/Homebrew/formula.rb:1282:in `block in brew'
	 4: from /opt/homebrew/Library/Homebrew/build.rb:178:in `block (2 levels) in install'
	 3: from /opt/homebrew/Library/Taps/riscv/homebrew-riscv/riscv-gnu-toolchain.rb:41:in `install'
	 2: from /opt/homebrew/Library/Homebrew/formula.rb:2225:in `system'
	 1: from /opt/homebrew/Library/Homebrew/formula.rb:2225:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2289:in `block in system': Failed executing: make (BuildError)
	9: from /opt/homebrew/Library/Homebrew/brew.rb:162:in `<main>'
	8: from /opt/homebrew/Library/Homebrew/brew.rb:174:in `rescue in <main>'
	7: from /opt/homebrew/Library/Homebrew/exceptions.rb:509:in `dump'
	6: from /opt/homebrew/Library/Homebrew/exceptions.rb:455:in `issues'
	5: from /opt/homebrew/Library/Homebrew/exceptions.rb:459:in `fetch_issues'
	4: from /opt/homebrew/Library/Homebrew/utils/github.rb:61:in `issues_for_formula'
	3: from /opt/homebrew/Library/Homebrew/utils/github.rb:30:in `search_issues'
	2: from /opt/homebrew/Library/Homebrew/utils/github.rb:160:in `search'
	1: from /opt/homebrew/Library/Homebrew/utils/github/api.rb:234:in `open_rest'
/opt/homebrew/Library/Homebrew/utils/github/api.rb:304:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)

**Comment by aswaterman** [comment]
Please report homebrew build failures on https://github.com/riscv-software-src/homebrew-riscv (and also check the issue tracker there to see if anyone else has seen the same problem).

**Comment by jim-wilson** [comment]
The last 15 lines of the build log don't show the error.  It looks like you did a parallel make, and something else failed long before the gdb build succeeded, so there is no error in the output you are showing.  You need to find the actual error and report that.  Try looking for the string "error:" in your build log.  Or just running make again should put the error near the end.
